// Focused 10-minute run content frozen by the 2026-09-21 L1 ruling.
globalThis.MVP_CONTENT = Object.freeze({
  run: Object.freeze({
    seed: 101,
    hp: 24,
    hpMax: 24,
    qi: 12,
    qiMax: 12,
    baseQiMax: 12,
    thoughts: 2,
    stones: 3,
    owned: Object.freeze({
      moonlight_gu: 1,
      small_light_gu: 1,
      stone_shell_gu: 1,
      vitality_grass_gu: 1,
      jade_skin_gu: 1,
    }),
  }),
  encounters: Object.freeze([
    Object.freeze({
      id: 'battle_1',
      type: 'battle',
      order: 1,
      title: '山道截杀',
      enemyId: 'ridge_hound',
      brief: '猎犬藏着一种反制式，先看清代价。',
    }),
    Object.freeze({ id: 'bazaar', type: 'bazaar', order: 2, title: '大巴扎' }),
    Object.freeze({
      id: 'battle_2',
      type: 'battle',
      order: 3,
      title: '雨沟追猎',
      enemyId: 'iron_hide_boar',
      brief: '铁皮山猪不接受无脑攻击，它会把鲁莽变成下一次冲撞。',
    }),
    Object.freeze({ id: 'forge', type: 'forge', order: 4, title: '炼蛊台' }),
    Object.freeze({
      id: 'elite',
      type: 'elite',
      order: 5,
      title: '高坡截击',
      enemyId: 'ridge_elite_scout',
      brief: '悍客先封你的出招顺序，再抽走剩余真元。',
    }),
    Object.freeze({
      id: 'boss',
      type: 'boss',
      order: 6,
      title: '雷冠封路',
      enemyId: 'thunder_crown_sovereign',
      brief: '雷冠狼王会记住你重复使用的蛊。',
    }),
    Object.freeze({ id: 'ending', type: 'ending', order: 7, title: '本局结算' }),
  ]),
  tradeOptions: Object.freeze([
    Object.freeze({
      id: 'secure',
      label: '光道积累',
      promise: '放弃未来的真元储备，换取稳定的信息与光道行动。',
      cost: Object.freeze({ stones: 3 }),
      gain: Object.freeze({ gu: Object.freeze({ small_light_gu: 2 }) }),
      consequence: '支付 3 元石，获得 2 只小光蛊。',
    }),
    Object.freeze({
      id: 'sacrifice',
      label: '力道换命',
      promise: '不要安全防御，用自己的身体制造破绽。',
      cost: Object.freeze({ gu: Object.freeze({ stone_shell_gu: 1 }) }),
      gain: Object.freeze({
        stones: 4,
        gu: Object.freeze({ white_boar_strength_gu: 1 }),
      }),
      consequence: '永久失去石皮蛊，获得白豕蛊与 4 元石。',
    }),
    Object.freeze({
      id: 'debt',
      label: '借月',
      promise: '提前得到修改敌人规则的能力，但留下道伤。',
      gain: Object.freeze({ gu: Object.freeze({ moon_glow_gu: 1 }) }),
      penalty: Object.freeze({ qiMax: 8, borrowedMoon: true }),
      consequence: '获得借来的月芒蛊；本局真元上限永久降至 8。',
    }),
  ]),
  forge: Object.freeze({
    recipeId: 'moonlight_glow',
    consume: Object.freeze({ moonlight_gu: 1, small_light_gu: 1 }),
    qiCost: 2,
    output: 'moon_glow_gu',
    preserveStones: 3,
    rule: '月芒蛊消耗 3 真元、1 气血、1 念头，冷却 2 回合；对已洞悉目标可压制反制与特殊效果，并降低本次敌方伤害 3。',
  }),
  /* V4 生存校准阀门：普通战胜利后恢复 2 气血 / 2 真元。不做节点、不做 UI、不做选择。
     Boss 前不额外满血满真元。前三场最多回 6 气血，受伤仍是长期代价。 */
  victoryRecovery: Object.freeze({ hp: 2, qi: 2 }),
  actions: Object.freeze({
    moonlight_gu: Object.freeze({
      label: '月光蛊',
      thought: 1,
      qi: 1,
      cooldown: 0,
      light: true,
      damage: 2,
      supportedDamage: 3,
      supportedQi: 0,
    }),
    small_light_gu: Object.freeze({
      label: '小光蛊',
      thought: 1,
      qi: 0,
      cooldown: 2,
      light: true,
      inspect: true,
      support: true,
    }),
    stone_shell_gu: Object.freeze({
      label: '石皮蛊',
      thought: 1,
      qi: 1,
      cooldown: 1,
      block: 5,
      chargeGuard: true,
    }),
    vitality_grass_gu: Object.freeze({
      label: '生机草蛊',
      thought: 1,
      qi: 0,
      cooldown: 0,
      heal: 1,
      light: true,
    }),
    jade_skin_gu: Object.freeze({
      label: '玉皮蛊',
      thought: 1,
      qi: 1,
      cooldown: 1,
      block: 3,
    }),
    white_boar_strength_gu: Object.freeze({
      label: '白豕蛊',
      thought: 1,
      qi: 0,
      cooldown: 1,
      damage: 2,
      woundedDamage: 5,
      breaksCounterWhenWounded: true,
    }),
    moon_glow_gu: Object.freeze({
      label: '月芒蛊',
      thought: 1,
      qi: 3,
      hp: 1,
      cooldown: 2,
      damage: 4,
      light: true,
      suppressWhenRevealed: true,
    }),
  }),
  enemyProfiles: Object.freeze({
    ridge_hound: Object.freeze({
      hp: 10,
      phaseAt: null,
      intents: Object.freeze([
        Object.freeze({
          id: 'stalk_pounce',
          label: '蓄扑',
          damage: 4,
          tag: 'charge',
          counterPool: Object.freeze(['intercept', 'draw_light']),
        }),
      ]),
    }),
    iron_hide_boar: Object.freeze({
      hp: 15,
      phaseAt: null,
      intents: Object.freeze([
        Object.freeze({ id: 'boar_charge_5', label: '獠牙冲撞', damage: 5, tag: 'charge', counter: 'iron' }),
        Object.freeze({ id: 'boar_wait', label: '蓄势', damage: 0, tag: 'wait' }),
        Object.freeze({ id: 'boar_charge_6', label: '獠牙冲撞', damage: 6, tag: 'charge', counter: 'iron' }),
      ]),
    }),
    ridge_elite_scout: Object.freeze({
      hp: 18,
      phaseAt: null,
      intents: Object.freeze([
        Object.freeze({
          id: 'seal_order',
          label: '封脉',
          damage: 0,
          kind: 'seal',
          counterPool: Object.freeze(['seal_first', 'seal_last']),
        }),
        Object.freeze({
          id: 'drain_qi',
          label: '噬元',
          damage: 0,
          kind: 'drain_qi',
          drainQi: 3,
        }),
        Object.freeze({ id: 'crossbow_shot', label: '弩箭贯击', damage: 4, tag: 'charge' }),
      ]),
    }),
    thunder_crown_sovereign: Object.freeze({
      hp: 28,
      phaseAt: 14,
      phaseOne: Object.freeze([
        Object.freeze({
          id: 'thunder_pounce',
          label: '雷冠贯落',
          damage: 5,
          tag: 'charge',
          counterPool: Object.freeze(['intercept', 'draw_light']),
        }),
      ]),
      phaseTwo: Object.freeze([
        Object.freeze({ id: 'burn_qi_3', label: '焚元', damage: 0, kind: 'burn_qi', burnQi: 3 }),
        Object.freeze({ id: 'thunder_pounce_2', label: '雷冠贯落', damage: 6, tag: 'charge' }),
      ]),
    }),
  }),
  counterRules: Object.freeze({
    intercept: Object.freeze({
      label: '迎击',
      detail: '直接攻击无效；每次出手额外损失 2 气血。',
    }),
    draw_light: Object.freeze({
      label: '逐光',
      detail: '若本回合未使用光道蛊，蓄扑伤害 +3。',
    }),
    iron: Object.freeze({
      label: '铁皮',
      detail: '直接攻击无效且不会击破铁皮；每次鲁莽攻击使下次冲撞 +1。',
    }),
    seal_first: Object.freeze({
      label: '封首',
      detail: '封住你本回合使用的第一只蛊，持续 1 回合。',
    }),
    seal_last: Object.freeze({
      label: '封尾',
      detail: '封住你本回合使用的最后一只蛊，持续 1 回合。',
    }),
  }),
  intel: Object.freeze({
    ridge_hound: Object.freeze({
      known: '公开：蓄扑，预计 4 伤。',
      unknown: '未知：迎击还是逐光。',
    }),
    iron_hide_boar: Object.freeze({
      known: '公开：冲撞与蓄势循环；冲撞伴有铁皮。',
      unknown: '未知：铁皮需要哪条路线击破。',
    }),
    ridge_elite_scout: Object.freeze({
      known: '公开：先封脉，再噬元，后直击。',
      unknown: '未知：封首还是封尾。',
    }),
    thunder_crown_sovereign: Object.freeze({
      known: '公开：一阶段试探，二阶段焚元并记住重复用蛊。',
      unknown: '未知：一阶段采用哪种反制式。',
    }),
  }),
});
